name: 'Generate PR with AI'
description: 'A GitHub Action that generates pull requests using AI (LLM).'
author: 'WillBooster Inc.'

# Define the inputs for your action
inputs:
  issue-number:
    description: 'The issue (or PR) number to reference when generating the PR'
    required: true
  planning-model:
    description: 'LLM to use for planning code changes. Must use llmlite format: provider/model (e.g., openai/gpt-4.1, azure/gpt-4.1, google/gemini-2.5-pro-preview-05-06, anthropic/claude-4-sonnet-latest, bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0, vertex/gemini-2.5-pro-preview-05-06)'
    required: false
  two-staged-planning:
    description: 'Enable two-staged planning: first select relevant files, then generate detailed implementation plans (increases LLM cost but improves code quality)'
    required: false
    default: 'true'
  reasoning-effort:
    description: 'Constrains effort on reasoning for reasoning models. Supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used.'
    required: false
  repomix-extra-args:
    description: 'Extra arguments for repomix when generating context for planning'
    required: false
    default: '--model gemini/gemini-2.5-pro-preview-05-06 --edit-format diff-fenced --chat-language English'
  aider-extra-args:
    description: 'Additional arguments to pass to the aider command'
    required: false
    default: '--compress --remove-empty-lines --include "src/**/*.{ts,tsx},**/*.md"'
  test-command:
    description: 'Command to run after Aider applies changes. If it fails, Aider will try to fix it.'
    required: false
  max-test-attempts:
    description: 'Maximum number of attempts to fix test failures'
    required: false
    default: '5'
  dry-run:
    description: 'Run without making actual changes (no branch creation, no PR)'
    required: false
    default: 'false'

# Define the runs configuration
runs:
  using: 'node20'
  main: 'dist/action.js'

# Add branding to make your action stand out in the marketplace
branding:
  icon: 'git-pull-request'
  color: 'blue'
