name: 'LLM PR Generator'
description: 'A GitHub Action that generates pull requests using LLMs'
author: 'WillBooster Inc.'

# Define the inputs for your action
inputs:
  issue-number:
    description: 'The issue (or PR) number to reference when generating the PR'
    required: true

# Define the outputs for your action
outputs:
  pr-description:
    description: 'The generated PR description'
    value: ${{ steps.generator.outputs.pr-description }}

# Define the runs configuration
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Print Hello World
      shell: bash
      run: echo "Hello, World!"

    - name: Extract versions from .tool-versions
      id: versions
      shell: bash
      run: |
        BUN_VERSION=$(grep "^bun " .tool-versions | cut -d' ' -f2)
        PYTHON_VERSION=$(grep "^python " .tool-versions | cut -d' ' -f2)
        echo "bun-version=$BUN_VERSION" >> $GITHUB_OUTPUT
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
        echo "Extracted versions from .tool-versions:"
        echo "Bun: $BUN_VERSION"
        echo "Python: $PYTHON_VERSION"

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ steps.versions.outputs.bun-version }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.versions.outputs.python-version }}
    - name: Install Aider
      shell: bash
      run: |
        echo "Installing Aider..."
        python -m pip install aider-install
        aider-install
        uv tool run --from aider-chat pip install boto3
    - name: Print versions
      shell: bash
      run: |
        bun --version
        python --version
        pip --version
        gh --version
        aider --version

    - name: Run main code
      shell: bash
      run: bun src/index.ts --issue ${{ inputs.issue-number }}

# Add branding to make your action stand out in the marketplace
branding:
  icon: 'git-pull-request'
  color: 'blue'
