name: 'Generate PR with LLM'
description: 'A GitHub Action that generates pull requests using LLMs.'
author: 'WillBooster Inc.'

# Define the inputs for your action
inputs:
  issue-number:
    description: 'The issue (or PR) number to reference when generating the PR'
    required: true

# Define the runs configuration
runs:
  using: 'node20'
  main: 'dist/index.js'

# Add branding to make your action stand out in the marketplace
branding:
  icon: 'git-pull-request'
  color: 'blue'
