name: 'LLM PR Generator'
description: 'A GitHub Action that generates pull requests using LLMs'
author: 'WillBooster Inc.'

# Define the outputs for your action
outputs:
  pr-description:
    description: 'The generated PR description'
    value: ${{ steps.generator.outputs.pr-description }}

# Define the runs configuration
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract versions from .tool-versions
      id: versions
      shell: bash
      run: |
        BUN_VERSION=$(grep "^bun " .tool-versions | cut -d' ' -f2)
        NODE_VERSION=$(grep "^nodejs " .tool-versions | cut -d' ' -f2)
        PYTHON_VERSION=$(grep "^python " .tool-versions | cut -d' ' -f2)
        echo "bun-version=$BUN_VERSION" >> $GITHUB_OUTPUT
        echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
        echo "Extracted versions from .tool-versions:"
        echo "Bun: $BUN_VERSION"
        echo "Node.js: $NODE_VERSION"
        echo "Python: $PYTHON_VERSION"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.versions.outputs.node-version }}

    - name: Print Node.js version
      shell: bash
      run: |
        echo "Node.js version:"
        node --version
        npm --version

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ steps.versions.outputs.bun-version }}

    - name: Print Bun version
      shell: bash
      run: |
        echo "Bun version:"
        bun --version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.versions.outputs.python-version }}

    - name: Print Python version
      shell: bash
      run: |
        echo "Python version:"
        python --version
        pip --version

    - name: Print GitHub CLI version
      shell: bash
      run: |
        echo "GitHub CLI version:"
        gh --version

    - name: Install Aider
      shell: bash
      run: |
        echo "Installing Aider..."
        python -m pip install aider-install
        aider-install

    - name: Print Aider version
      shell: bash
      run: |
        echo "Aider version:"
        aider --version

    - name: Generate PR description
      id: generator
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/generate-pr.sh
        ${{ github.action_path }}/generate-pr.sh

# Add branding to make your action stand out in the marketplace
branding:
  icon: 'git-pull-request'
  color: 'blue'
