name: Generate PR (example)

on:
  issues:
    types:
      - labeled

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    # Only run if the label name includes 'llm-pr' and an issue number is available
    if: contains(github.event.label.name, 'llm-pr') && github.event.issue.number != null
    steps:
      - uses: actions/checkout@v4
      - name: Generate PR with LLMs
        uses: ./ # This references the action in the current repository
        with:
          issue-number: ${{ github.event.issue.number }}
        env:
          # for Amazon (Bedrock)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: us-west-2
          # for Google (AI Studio)
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # for OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
